apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-exploration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space-exploration
  template:
    metadata:
      labels:
        app: space-exploration
    spec:
      containers:
      - name: space-exploration
        image: stevegreghatch/space-exploration:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
