apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: api.history-from-the-frontier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: space-exploration
                port:
                  number: 8080
#          - path: /persistence
#            pathType: Prefix
#            backend:
#              service:
#                name: persistence-service
#                port:
#                  number: 8081
