apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-space-exploration-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: address
    networking.gke.io/managed-certificates: managed-cert-space-exploration
    kubernetes.io/ingress.class: gce
spec:
  defaultBackend:
    service:
      name: api-space-exploration-service
      port:
        number: 8080