from enum import Enum


class MissionName(str, Enum):
    BEACH_ABORT = "BEACH_ABORT"
    BIG_JOE_1 = "BIG_JOE_1"
    LITTLE_JOE_1 = "LITTLE_JOE_1"
    LITTLE_JOE_1A = "LITTLE_JOE_1A"
    LITTLE_JOE_1B = "LITTLE_JOE_1B"
    LITTLE_JOE_2 = "LITTLE_JOE_2"
    LITTLE_JOE_5 = "LITTLE_JOE_5"
    LITTLE_JOE_5A = "LITTLE_JOE_5A"
    LITTLE_JOE_5B = "LITTLE_JOE_5B"
    LITTLE_JOE_6 = "LITTLE_JOE_6"
    MERCURY_ATLAS_1 = "MERCURY_ATLAS_1"
    MERCURY_ATLAS_2 = "MERCURY_ATLAS_2"
    MERCURY_ATLAS_3 = "MERCURY_ATLAS_3"
    MERCURY_ATLAS_4 = "MERCURY_ATLAS_4"
    MERCURY_ATLAS_5 = "MERCURY_ATLAS_5"
    MERCURY_REDSTONE_1 = "MERCURY_REDSTONE_1"
    MERCURY_REDSTONE_1A = "MERCURY_REDSTONE_1A"
    MERCURY_REDSTONE_2 = "MERCURY_REDSTONE_2"
    MERCURY_REDSTONE_BD = "MERCURY_REDSTONE_BD"
    MERCURY_SCOUT_1 = "MERCURY_SCOUT_1"


# Example usage:
if __name__ == "__main__":
    print(MissionName.MERCURY_ATLAS_3.value)
